config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :list, on: :collection
      end
      resources :questions, only: [:index, :show, :create], shallow: true do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

  concern :votable do
    member do
      post 'vote_up'
      post 'vote_down'
      delete 'cancel_vote'
    end
  end

  devise_scope :user do
    post 'set_email', to: 'omniauth_callbacks#set_email'
    post 'subscribe_digest', to: 'users#subscribe_digest'
    delete 'unsubscribe_digest', to: 'users#unsubscribe_digest'
  end

  resources :questions, concerns: [:votable] do
    resources :answers, concerns: [:votable], shallow: true do
      patch 'set_best', on: :member
    end
    resources :comments, only: [:new,:create], defaults: { commentable: 'question' } 
    resources :subscriptions, only: [:create, :destroy], shallow: true   
  end

  resources :answers, only: [] do
    resources :comments, only: [:new,:create], defaults: { commentable: 'answer' }
  end

  resources :comments, only: :destroy
  
  resources :attachments, only: :destroy

  resource :search, only: :show  

  root 'questions#index'

  mount ActionCable.server => '/cable'

  get 'terms' => 'pages#terms'
  get 'policy' => 'pages#policy'    
end

app/models/question.rb
class Question < ApplicationRecord
  include Attachable
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  belongs_to :user

  validates :title, :body, length: { minimum: 5, maximum: 255 }

  after_create :subscribe_author

  scope :ordered_by_time, -> { order(created_at: :desc) }

  private

  def subscribe_author
    subscriptions.create(user_id: user.id)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource

  def index
    respond_with @questions = Question.all
  end

  def create
    @question = current_resource_owner.questions.create(question_params)
    respond_with @question
  end

  def show
    respond_with @question = Question.find(params[:id])
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_question, only: [:show, :destroy, :update]
  before_action :new_answer, only: :show
  before_action :check_subscription, only: :show

  after_action :publish_question, only: [:create]
  after_action :delete_question_broadcast, only: [:destroy]

  respond_to :js, :json

  authorize_resource

  def new
    respond_with(@question = Question.new)
    ahoy.track "Attemt to create question"
  end

  def create
    @question = current_user.questions.create(question_params)
    respond_with(@question)
  end

  def index
    respond_with(@questions = Question.all)
  end

  def destroy
    respond_with(@question.destroy)
  end

  def update
    respond_with(@question.update(question_params))
  end

  def show
    respond_with(@question)
  end

  private

  def new_answer
    @answer = @question.answers.new
  end

  def publish_question
    return if @question.errors.any?
    data = ApplicationController.render(
      partial: 'questions/question',
      locals: { question: @question }
    )
    broadcast_data(data)
  end

  def delete_question_broadcast
    data = {
      action: :delete,
      question_id: @question.id
    }
    broadcast_data(data)
  end

  def broadcast_data(data)
    ActionCable.server.broadcast('questions', data)
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :_destroy, :id])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def check_subscription
    @subscription = Subscription.find_or_initialize_by(user: current_user, question: @question) if
      can?(:create, Subscription)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_new.html.slim
= form_for Question.new do |f|
  p
  = f.label :title
  = f.text_field :title
  p
  = f.label :body
  = f.text_area :body
  p Attachments:
  p

    = link_to_add_association 'Add file', f, :attachments, partial: 'attachments/attachment_fields'
  p
  = f.submit 'Create'

app/views/questions/_question.html.slim
.collection-item id = dom_id(question)
  b = question.title
  br
  = link_to 'Show question', question
  hr

app/views/questions/_question_show.html.slim
.question_title  
  b = @question.title
br
.question_body
  p = @question.body
p Attachments:
ul
  = render 'attachments/attachments', attachable: @question
- if can?(:edit, @question)
  p = button_to 'Delete question', @question, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you shure?' }
  p = button_to 'Edit question', '#', class: 'edit-question-link btn btn-warning', data: { question_id: @question.id}
  p
  .row 
    = form_for @question, remote: true do |f|  
      .col-lg-10 
        = f.label :title
        .edit-question-errors   
        p = f.text_field :title, class:"form-control"
        p = f.label :body
        p = f.text_area :body, class:"form-control"
        = f.submit 'Save', class: "btn btn-primary"
   

app/views/questions/_subscription.html.slim
- if @subscription.persisted?
    = button_to 'Unsubscribe', subscription_path(@subscription), remote: true, method: :delete,  class: 'subscribe-link btn btn-warning'
- else
    = button_to 'Subscribe', question_subscriptions_path(@question), remote: true, method: :post,  class: 'subscribe-link btn btn-success'

app/views/questions/index.html.slim
- content_for :title
  'Q&A time - All questions
- if can?(:create, Question)
  p = link_to 'Ask question', new_question_path, class: "btn btn-primary"
- else
  p
    i You must sign in first for create questions
br
.questions-list.collection
  - if @questions.empty?
    b Questions list is empty
  - else
    = render @questions.ordered_by_time

app/views/questions/new.html.slim
.container
  = form_for @question do |f|
    p
      .row
        .col-sm-10
          = f.label :title
          = f.text_field :title, class:"form-control"
    p
      .row
        .col-sm-10
          = f.label :body
          = f.text_area :body, class:"form-control"
    p Attachments:
    p = link_to_add_association 'Add file', f, :attachments, partial: 'attachments/attachment_fields'
    p = f.submit 'Create', class: "btn btn-primary"

app/views/questions/show.html.slim
-content_for :title
  = @question.title
- cache [can?(:vote, @question), user_signed_in?, can?(:destroy, @question), can?(:edit, @question),
  can?(:create, Subscription) && can?(:destroy, Subscription), @question, @subscription] do
  .question data-id="#{@question.id}"
    .row
      .col-md-1.col-sm-2.col-xs-3
        = render 'votes/votes', votable: @question
      .col-sm-6
        = render 'questions/question_show', question: @question
        .div id="Question-#{@question.id}-comments" class = 'question-comments'
          = render @question.comments
        .question-new-comment
          - if can?(:create, Comment)
            p = button_to 'Add comment', new_question_comment_path(@question), remote: true,
           method: :get, class:"btn btn-info"
        .subscription
          - if can?(:create, Subscription)
            p = render 'questions/subscription'
  hr
  .answers
    - if @question.answers.empty?
      b No answers
    - else
      = render @question.answers
  .new_answer.container
    - if can?(:create, Answer)
        .row
          .col-lg-6
            = form_for [@question, @answer], remote: true do |f|
              = f.label :body, 'Answer'
              .answer-errors
              = f.text_area :body, id: "new-answer-body", class: "form-control"
              p = link_to_add_association 'Add file', f, :attachments, partial: 'attachments/attachment_fields'
              p = f.submit 'Create answer', class: "btn btn-primary"
    - else
      i You must sign in first for create answer

app/views/questions/update.js.erb
<% if @question.errors.present?%>
  <% @question.errors.full_messages.each do |message| %>
    $('.edit-question-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.edit_question').hide();  
  $('.edit-question-errors').html('')
  $('.edit-question-link').show();
  $('.question_body').html('<%= j @question.body %>');
  $('.question_title').html('<%= j @question.title %>');  
  $('.question_body').show();
  $('.question_title').show();    
<% end %>