config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :list, on: :collection
      end
      resources :questions, only: [:index, :show, :create], shallow: true do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

  concern :votable do
    member do
      post 'vote_up'
      post 'vote_down'
      delete 'cancel_vote'
    end
  end

  devise_scope :user do
    post 'set_email', to: 'omniauth_callbacks#set_email'
    post 'subscribe_digest', to: 'users#subscribe_digest'
    delete 'unsubscribe_digest', to: 'users#unsubscribe_digest'
  end

  resources :questions, concerns: [:votable] do
    resources :answers, concerns: [:votable], shallow: true do
      patch 'set_best', on: :member
    end
    resources :comments, only: [:new,:create], defaults: { commentable: 'question' } 
    resources :subscriptions, only: [:create, :destroy], shallow: true   
  end

  resources :answers, only: [] do
    resources :comments, only: [:new,:create], defaults: { commentable: 'answer' }
  end

  resources :comments, only: :destroy
  
  resources :attachments, only: :destroy

  resource :search, only: :show  

  root 'questions#index'

  mount ActionCable.server => '/cable'

  get 'terms' => 'pages#terms'
  get 'policy' => 'pages#policy'    
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Attachable
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user

  validates :body, length: { minimum: 5 }

  after_create_commit { AnswersNotificationJob.perform_later self }

  default_scope { order('best DESC, created_at ASC') }

  def set_best
    transaction do
      Answer.where(question_id: question.id, best: true).update_all(best: false)
      update!(best: true)
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!, only: [:create, :destroy, :update, :set_best]
  before_action :set_question,       only: [:create]
  before_action :set_answer,         only: [:destroy, :update, :set_best]

  after_action :publish_answer, only: [:create]
  after_action :delete_answer_broadcast, only: [:destroy]

  respond_to :js, :json

  authorize_resource

  def create
    @answer = current_user.answers.create(answer_params.merge(question_id: @question.id))
    respond_with(@answer)
  end

  def destroy
    respond_with(@answer.destroy)
  end

  def update
    respond_with(@answer.update(answer_params))
  end

  def set_best
    respond_with(@answer.set_best)
  end

  private

  def publish_answer
    return if @answer.errors.any?
    data = {
      type: :answer,
      answer: @answer,
      question_author_id: @question.user_id,
      rating: @answer.rating,
      attachments: @answer.attachments.as_json(methods: :with_meta)
    }
    broadcast_data(data)
  end

  def delete_answer_broadcast
    @question = @answer.question
    data = {
      action: :delete,
      type: :answer,
      answer_id: @answer.id
    }
    broadcast_data(data)
  end

  def broadcast_data(data)
    ActionCable.server.broadcast("question_answers_#{@question.id}", data)
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :_destroy, :id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource
  before_action :set_question, except: :show

  def index
    respond_with @answers = @question.answers
  end

  def show
    respond_with @answer = Answer.find(params[:id])
  end

  def create
    @answer = @question.answers.create(answer_params.merge(user: current_resource_owner))
    respond_with @answer
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/1set_best.js.erb
$('.answers').html('<%= j render @answer.question.answers %>');

app/views/answers/_answer.html.slim
- cache [answer, can?(:set_best, answer), can?(:edit, answer), can?(:delete, answer), user_signed_in?, answer.best] do
  - if answer.persisted?
    .answer.container id = "answer-#{answer.id}"
      .row
        .col-md-1.col-sm-2.col-xs-3
          = render 'answers/best', answer: answer
          = render 'votes/votes', votable: answer
        .col-xs-8
          p id="edited-answer-#{answer.id}"
            = answer.body
            = render 'attachments/attachments', attachable: answer
            - if can?(:edit, answer)
              p = button_to 'Delete answer', answer, method: :delete, remote: true, class: 'btn btn-danger btn-sm',
               data: { answer_id: answer.id, confirm: 'Are you shure?' }
              p = button_to 'Edit', '#', class: 'edit-answer-link btn btn-warning btn-sm', data: { answer_id: answer.id}
              p = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}"} do |f|
                .row
                  .col-lg-8
                    = f.label :body, 'Answer'
                    .edit-answer-errors
                    = f.text_area :body, class:"form-control"
                    p.add-file
                      = link_to_add_association 'Add file', f, :attachments, partial: 'attachments/attachment_fields'
                    = f.submit 'Save', class: "btn btn-info"
      .row
        .col-md-1.col-sm-2.col-xs-3
        .col-xs-8
          div id="Answer-#{answer.id}-comments" class="answer-comments"
            =render answer.comments
          .answer-new-comment
            - if can?(:create, Comment)
              = button_to 'Add comment', new_answer_comment_path(answer), remote: true, method: :get, class:"btn btn-info btn-sm"
      .row  
        hr

app/views/answers/_best.html.slim
.text-center
  - if answer.best
    .h4
      span.label.label-success BEST
  - else
    - if can?(:set_best, answer)
      p= button_to 'Set best', set_best_answer_path(answer), method: :patch, remote: true, class: 'btn btn-success btn-sm'

app/views/answers/_edited_answer.html.slim
= answer.body        
= render 'attachments/attachments', attachable: answer 
      p         
- if can?(:edit, answer)
  p = button_to 'Delete answer', answer, method: :delete, remote: true, class: 'btn btn-danger btn-sm', data: { answer_id: answer.id, confirm: 'Are you shure?' }
  p = button_to 'Edit', '#', class: 'edit-answer-link btn btn-warning btn-sm', data: { answer_id: answer.id} 
  p 
  = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}"} do |f|
    .row
      .col-lg-8
        = f.label :body, 'Answer'
        .edit-answer-errors
        = f.text_area :body, class:"form-control" 
        p
        .add-file
          = link_to_add_association 'Add file', f, :attachments, partial: 'attachments/attachment_fields'
        = f.submit 'Save', class: "btn btn-info" 

app/views/answers/create.js.erb
<% if @answer.errors.present?%>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.answer-errors').html('')
  $('#new-answer-body').val('')
<% end %>

app/views/answers/destroy.js.erb
$('#answer-<%= @answer.id %>').remove();

app/views/answers/set_best.js.erb
$('.answers').html('<%= j render @answer.question.answers %>');

app/views/answers/update.js.erb
<% if @answer.errors.present?%>
  <% @answer.errors.full_messages.each do |message| %>
    $('.edit-answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.edit-answer-errors').html('')
  $('form#edit-answer-<%= @answer.id %>').hide();
  $('#edited-answer-<%= @answer.id %>').show();
  $('#answer-<%= @answer.id %>').html('<%= j render 'answers/answer', answer: @answer  %> '); 
  $('.edit-answer-link').show();
<% end %>