config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :list, on: :collection
      end
      resources :questions, only: [:index, :show, :create], shallow: true do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

  concern :votable do
    member do
      post 'vote_up'
      post 'vote_down'
      delete 'cancel_vote'
    end
  end

  devise_scope :user do
    post 'set_email', to: 'omniauth_callbacks#set_email'
    post 'subscribe_digest', to: 'users#subscribe_digest'
    delete 'unsubscribe_digest', to: 'users#unsubscribe_digest'
  end

  resources :questions, concerns: [:votable] do
    resources :answers, concerns: [:votable], shallow: true do
      patch 'set_best', on: :member
    end
    resources :comments, only: [:new,:create], defaults: { commentable: 'question' } 
    resources :subscriptions, only: [:create, :destroy], shallow: true   
  end

  resources :answers, only: [] do
    resources :comments, only: [:new,:create], defaults: { commentable: 'answer' }
  end

  resources :comments, only: :destroy
  
  resources :attachments, only: :destroy

  resource :search, only: :show  

  root 'questions#index'

  mount ActionCable.server => '/cable'

  get 'terms' => 'pages#terms'
  get 'policy' => 'pages#policy'    
end

app/models/search.rb
class Search
  OBJECTS = %w[All Questions Answers Comments Users].freeze

  def self.find(query, object)
    return nil if query.try(:blank?) || !OBJECTS.include?(object)
    query = ThinkingSphinx::Query.escape(query)
    if object == 'All'
      ThinkingSphinx.search query
    else
      ThinkingSphinx.search(query, classes: [object.classify.constantize])
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  skip_authorization_check

  def show
    @query = params[:query]
    @object = params[:object]
    @result = Search.find(@query, @object) if @query.present?
  end
end

app/views/searches/_answer.html.slim
= link_to "Answer for: #{item.question.title}", question_path(item.question)
p = item.body

app/views/searches/_comment.html.slim
- if item.commentable.is_a? Question
  = link_to "Comment for: #{item.commentable.title}", question_path(item.commentable)
  p = item.body
- else
  = link_to "Comment for: #{item.commentable.question.title}", question_path(item.commentable.question)
  p = item.body

app/views/searches/_question.html.slim
= link_to "Question: #{item.title}", question_path(item)
p = item.body

app/views/searches/_user.html.slim
= "User: #{item.email}"

app/views/searches/show.html.slim
h1 Search results
.search_results
  - if @result
    ul
      - @result.each do |item|
        li
          = render "#{item.class.name.downcase}", item: item
  - else
    |No results