config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :list, on: :collection
      end
      resources :questions, only: [:index, :show, :create], shallow: true do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

  concern :votable do
    member do
      post 'vote_up'
      post 'vote_down'
      delete 'cancel_vote'
    end
  end

  devise_scope :user do
    post 'set_email', to: 'omniauth_callbacks#set_email'
    post 'subscribe_digest', to: 'users#subscribe_digest'
    delete 'unsubscribe_digest', to: 'users#unsubscribe_digest'
  end

  resources :questions, concerns: [:votable] do
    resources :answers, concerns: [:votable], shallow: true do
      patch 'set_best', on: :member
    end
    resources :comments, only: [:new,:create], defaults: { commentable: 'question' } 
    resources :subscriptions, only: [:create, :destroy], shallow: true   
  end

  resources :answers, only: [] do
    resources :comments, only: [:new,:create], defaults: { commentable: 'answer' }
  end

  resources :comments, only: :destroy
  
  resources :attachments, only: :destroy

  resource :search, only: :show  

  root 'questions#index'

  mount ActionCable.server => '/cable'

  get 'terms' => 'pages#terms'
  get 'policy' => 'pages#policy'    
end

app/views/layouts/application.html.slim
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title = content_for?(:title) ? yield(:title) : "Q&A time"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = action_cable_meta_tag
    = Gon::Base.render_data
    = favicon_link_tag '/pics/favicon.ico', rel: 'shortcut icon'
  body
    .navbar.navbar-default.navbar-static-top
      .container
        a.navbar-brand href="#{root_url}"Q&A time
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        .col-lg-2
          .navbar-text
            strong = link_to 'All questions', questions_path
        .navbar-collapse.collapse.navbar-responsive-collapse
          .row
            .col-md-offset-10.col-sm-offset-9
              - if user_signed_in?
                = current_user.email
                p = link_to 'Sign out', destroy_user_session_path, method: :delete
                p = link_to 'My account', edit_user_registration_path
              - else
                p = link_to 'Sign in', new_user_session_path
        .row
          .col-md-offset-7.col-sm-offset-6
            = render 'common/search_form'
    .container
      .row
        .col-12
          - if notice
            .alert.alert-success.mt-4
              = notice
          - if alert
            .alert.alert-danger.mt-4
              = alert
          = yield
      footer
        br
        p
          '&copy; Mikhail Balashov
          = Time.now.year